name: CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Build Docker Image
        run: docker build -t badboy2977/tradematefr .
      
      - name: Publish image to Docker Hub
        run: docker push badboy2977/tradematefr:latest   

  deploy: 
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from Docker Hub
        run: sudo docker pull badboy2977/tradematefr:latest 
      
      - name: Delete Old Container
        run: sudo docker rm -f reactContainer || true
      
      - name: Run Docker Container
        run: sudo docker run -d -p 80:3000 --name reactContainer badboy2977/tradematefr:latest 
 
